# Dockerfile for running Playwright tests
# FROM mcr.microsoft.com/playwright:v1.48.0-jammy
# WORKDIR /app
# COPY package*.json ./
# RUN npm ci
# COPY . .

# # Run tests 
# CMD CMD ["npm", "run", "test:allure"]
